Controllers/BookController.cs
using BookStore_Use_Asp_Net_Core_5_MVC.Data;
using BookStore_Use_Asp_Net_Core_5_MVC.IRepository;
using BookStore_Use_Asp_Net_Core_5_MVC.Models;
using BookStore_Use_Asp_Net_Core_5_MVC.SessionExtensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BookStore_Use_Asp_Net_Core_5_MVC.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _repo;
        private readonly AppDbContext _db;

        public BookController(IBookRepository repo, AppDbContext db)
        {
            _repo = repo;
            _db = db;
        }

        //Get all Books
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAll());
        }

        //Get spcicific book details
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            return View(await _repo.GetOne(id));
        }


        //Http Get for AddBookAndEdit Book
        [HttpGet]
        public async Task<IActionResult> Add_Edit(int? id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                return View(await _repo.GetOne(id));
            }
        }

        //Http Post for AddBookAndEdit Books
        [HttpPost]
        public async Task<IActionResult> Add_Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.Id > 0)
                {
                    var item = await _repo.GetOne(book.Id);
                    book.ImgeUrl = item.ImgeUrl;
                    int id = await _repo.Edit(book);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    int id = await _repo.Add(book);
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(book);
        }


        //Http Get for Delete Book
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            bool IsDelete = await _repo.Delete(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

Controllers/CategoryController.cs
using BookStore_Use_Asp_Net_Core_5_MVC.IRepository;
using BookStore_Use_Asp_Net_Core_5_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore_Use_Asp_Net_Core_5_MVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _repo;
        public CategoryController (ICategoryRepository repo)
        {
           _repo = repo;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAll());
        }

        [HttpGet]
        public async Task<IActionResult> Add_Edit(int? id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                return View(await _repo.GetOne(id));
            }
                
        }

        [HttpPost]
        public async Task<IActionResult> Add_Edit(Category category_)
        {
             
            if (ModelState.IsValid)
            {
                if (category_.Id > 0)
                {
                    int id = await _repo.Edit(category_);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    int id = await _repo.Edit(category_);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(category_);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
               await _repo.Delete(id);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/LanguageController.cs
using BookStore_Use_Asp_Net_Core_5_MVC.IRepository;
using BookStore_Use_Asp_Net_Core_5_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore_Use_Asp_Net_Core_5_MVC.Controllers
{
    public class LanguageController : Controller
    {
        private readonly ILanguageRepository _repo;
        public LanguageController(ILanguageRepository repo)
        {
           _repo = repo;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAll());
        }

        [HttpGet]
        public async Task<IActionResult> Add_Edit(int? id)
        {
            if (id == null)
            {
                return View();
            }
            else
            {
                return View(await _repo.GetOne(id));
            }
                
        }

        [HttpPost]
        public async Task<IActionResult> Add_Edit(Language language_)
        {
             
            if (ModelState.IsValid)
            {
                if (language_.Id > 0)
                {
                    int id = await _repo.Edit(language_);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    int id = await _repo.Edit(language_);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(language_);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
               await _repo.Delete(id);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Shared/_ButtonGroup.cshtml
@model int

<div class="btn-group" role="group" >
    <a   asp-action="Add_Edit" asp-route-id="@Model"  class="btn btn-info">Edit</a>
    <a onclick="myclick()"  asp-action="Delete" asp-route-id="@Model"  class="btn btn-danger">Delete</a>
</div>

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light ">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @{
                        if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">Language</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark text-lg-right" asp-controller="Account" asp-action="LogOut">LogOut</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogIn">LogIn</a>
                            </li>
                        }
                    }

                </ul>
            </div>
        </div>
    </nav>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginInfo.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager

<div>
    @{ 
        if (_signInManager.IsSignedIn(User))
        {

        }
    }
</div>